### ISSUE TITLE
I stake 0.002 rBTC，but it can`t work，how can I solove it?

### ISSUE THREAD

**Issue by bemvp** [btc-vision/opwallet#8]
look that picture ,I don`t know what happen ？I stake 0.002 rBTC，but it can`t work，how can I solove it?
![image](https://github.com/user-attachments/assets/d5563297-5ce8-4b9a-a811-563c02359b33)

**Comment by impredmet** [comment]
hello, is it still working? normally not, update your opwallet version and everything should work normally.

**Comment by bemvp** [comment]
@impredmet thank you  I will try it now

**Comment by bemvp** [comment]
How can I import wallet accounts from my old wallet to the newly updated wallet? I have more than twenty of them. Importing them one by one is too troublesome. Is there any quick method?
@impredmet thank you for your answer

**Comment by impredmet** [comment]
@bemvp at the moment, you have to manually import all the wallets you own. opwallet will soon be added to the chrome store to solve this problem.

**Comment by BlobMaster41** [comment]
Resolved
